export const stateList = [
    { label: 'Andhra Pradesh', value: 'ap' },
    { label: 'Arunachal Pradesh', value: 'ar' },
    { label: 'Assam', value: 'as' },
    { label: 'Bihar', value: 'br' },
    { label: 'Chhattisgarh', value: 'cg' },
    { label: 'Goa', value: 'ga' },
    { label: 'Gujarat', value: 'gj' },
    { label: 'Haryana', value: 'hr' },
    { label: 'Himachal Pradesh', value: 'hp' },
    { label: 'Jharkhand', value: 'jh' },
    { label: 'Karnataka', value: 'ka' },
    { label: 'Kerala', value: 'kl' },
    { label: 'Madhya Pradesh', value: 'mp' },
    { label: 'Maharashtra', value: 'mh' },
    { label: 'Manipur', value: 'mn' },
    { label: 'Meghalaya', value: 'ml' },
    { label: 'Mizoram', value: 'mz' },
    { label: 'Nagaland', value: 'nl' },
    { label: 'Odisha', value: 'od' },
    { label: 'Punjab', value: 'pb' },
    { label: 'Rajasthan', value: 'rj' },
    { label: 'Sikkim', value: 'sk' },
    { label: 'Tamil Nadu', value: 'tn' },
    { label: 'Telangana', value: 'tg' },
    { label: 'Tripura', value: 'tr' },
    { label: 'Uttar Pradesh', value: 'up' },
    { label: 'Uttarakhand', value: 'ut' },
    { label: 'West Bengal', value: 'wb' }
]