export const DELETE_SUPPLIER_POPUP_CODE = "POPUP001";
export const RESET_FORM_POPUP_CODE = "POPUP002";
export const UPDATE_RECORD_POPUP_CODE = "POPUP003";
export const ACCESS_CONTROL_POPUP_CODE = "POPUP004";
export const TABLE_LAYOUT_POPUP_CODE = "POPUP005";
export const SAVE_RECORD_POPUP_CODE = "POPUP006";

// react reducer constants

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CURRENT_USER_SCHEDULE_REQUEST = "CURRENT_USER_SCHEDULE_REQUEST";
export const CURRENT_USER_SCHEDULE_SUCCESS = "CURRENT_USER_SCHEDULE_SUCCESS";
export const CURRENT_USER_SCHEDULE_FAILURE = "CURRENT_USER_SCHEDULE_FAILURE";

export const SCHEDULE_CREATE_REQUEST = "SCHEDULE_CREATE_REQUEST";
export const SCHEDULE_CREATE_SUCCESS = "SCHEDULE_CREATE_SUCCESS";
export const SCHEDULE_CREATE_FAILURE = "SCHEDULE_CREATE_FAILURE";

export const SCHEDULE_UPDATE_REQUEST = "SCHEDULE_UPDATE_REQUEST";
export const SCHEDULE_UPDATE_SUCCESS = "SCHEDULE_UPDATE_SUCCESS";
export const SCHEDULE_UPDATE_FAILURE = "SCHEDULE_UPDATE_FAILURE";

export const SCHEDULE_DELETE_REQUEST = "SCHEDULE_DELETE_REQUEST";
export const SCHEDULE_DELETE_SUCCESS = "SCHEDULE_DELETE_SUCCESS";
export const SCHEDULE_DELETE_FAILURE = "SCHEDULE_DELETE_FAILURE";

export const SME_AVAILABILITY_REQUEST = "SME_AVAILABILITY_REQUEST";
export const SME_AVAILABILITY_SUCCESS = "SME_AVAILABILITY_SUCCESS";
export const SME_AVAILABILITY_FAILURE = "SME_AVAILABILITY_FAILURE";

export const EXTERNALIZATION_ACTIVITY_REQUEST =
  "EXTERNALIZATION_ACTIVITY_REQUEST";
export const EXTERNALIZATION_ACTIVITY_SUCCESS =
  "EXTERNALIZATION_ACTIVITY_SUCCESS";
export const EXTERNALIZATION_ACTIVITY_FAILURE =
  "EXTERNALIZATION_ACTIVITY_FAILURE";

export const SCHEDULE_UPDATE_MODAL = "SCHEDULE_UPDATE_MODAL";
export const SCHEDULE_DELETE_MODAL = "SCHEDULE_DELETE_MODAL";

export const RESET_SCHEDULED_REDUCER_DATA = "RESET_SCHEDULED_REDUCER_DATA";

export const REPORTS_REQUESTED = "REPORTS_REQUESTED";
export const SME_SUGGESTION_REQUESTED = "SME_SUGGESTIONS_REQUESTED";
export const REPORTS_SUCCESS = "REPORTS_SUCCESS";
export const SME_SUGGESTION_SUCCESS = "SME_SUGGESTION_SUCCESS";
export const REPORTS_FAILURE = "REPORTS_FAILURE";
